# === Verwerk iDRAC logs (RFC5424) naar afzonderlijk bestand ===
template(name="IdracRaw" type="string" string="%rawmsg%\n")

if (
  $fromhost-ip == '10.0.1.61' or
  $fromhost-ip == '10.0.1.62' or
  $fromhost-ip == '10.0.1.63' or
  $fromhost-ip == '10.0.1.80' or
  $fromhost-ip == '10.0.1.81' or
  $fromhost-ip == '10.0.1.85'
) then {
    action(
        type="omfile"
        file="/var/log/idrac.log"
        template="IdracRaw"
    )
    stop
}
