# === iDRAC syslog listener op custom poorten ===
# UDP listener
module(load="imudp")
input(type="imudp"
      port="10514"
      #address="10.0.1.121"
      ratelimit.interval="0"   # geen throttling
      ratelimit.burst="0"      # 0 = unlimited
)
